### ISSUE TITLE
Is it dsdc cable ?

### ISSUE THREAD

**Issue by ghost** [0x7ff/eclipsa#11]
Hi Dude.

I trying to playing with your code for A8,A9 and A9X only.
When i run, it waiting for the connection....

Please kindly help this

**Comment by 0x7ff** [comment]
Hey iyogasukma,
You don't need a DCSD cable to run this, any lightning to USB-A cable should work. Possible solutions for this problem are:
a) This tool does not support A9X as the memory leak is patched, so wait for ipwndfu to update. Sadly, I don't have that device.
b) Your fork is old, so it doesn't support older macOS versions, you should update your fork.
c) Your device must be in DFU mode.
I hope these will work for you.
